// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaLaboratorio.EFCore;

#nullable disable

namespace PruebaLaboratorio.EFCore.Migrations
{
    [DbContext(typeof(LaboratorioDBContext))]
    [Migration("20231018232446_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaLaborario.Entities.Elemento", b =>
                {
                    b.Property<int>("ElementoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ElementoId");

                    b.ToTable("Elementos");
                });

            modelBuilder.Entity("PruebaLaborario.Entities.Sucursal", b =>
                {
                    b.Property<int>("SucursalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SucursalId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SucursalId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("PruebaLaborario.Entities.Tecnico", b =>
                {
                    b.Property<int>("TecnicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TecnicoId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<decimal>("SueldoBase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TecnicoId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("PruebaLaborario.Entities.TecnicoElemento", b =>
                {
                    b.Property<int>("TecnicoElementoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TecnicoElementoId"));

                    b.Property<int>("CantidadAsignada")
                        .HasColumnType("int");

                    b.Property<int>("ElementoId")
                        .HasColumnType("int");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int");

                    b.HasKey("TecnicoElementoId");

                    b.HasIndex("ElementoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("TecnicoElementos");
                });

            modelBuilder.Entity("PruebaLaborario.Entities.Tecnico", b =>
                {
                    b.HasOne("PruebaLaborario.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("PruebaLaborario.Entities.TecnicoElemento", b =>
                {
                    b.HasOne("PruebaLaborario.Entities.Elemento", "Elemento")
                        .WithMany()
                        .HasForeignKey("ElementoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaLaborario.Entities.Tecnico", "Tecnico")
                        .WithMany("ElementosAsignados")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elemento");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("PruebaLaborario.Entities.Tecnico", b =>
                {
                    b.Navigation("ElementosAsignados");
                });
#pragma warning restore 612, 618
        }
    }
}
